/* Auto-generated by genmsg_cpp for file /home/billy/ros/stacks/pr2_controllers_msgs/msg/PointHeadFeedback.msg */
#ifndef PR2_CONTROLLERS_MSGS_MESSAGE_POINTHEADFEEDBACK_H
#define PR2_CONTROLLERS_MSGS_MESSAGE_POINTHEADFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pr2_controllers_msgs
{
template <class ContainerAllocator>
struct PointHeadFeedback_ {
  typedef PointHeadFeedback_<ContainerAllocator> Type;

  PointHeadFeedback_()
  : pointing_angle_error(0.0)
  {
  }

  PointHeadFeedback_(const ContainerAllocator& _alloc)
  : pointing_angle_error(0.0)
  {
  }

  typedef double _pointing_angle_error_type;
  double pointing_angle_error;


private:
  static const char* __s_getDataType_() { return "pr2_controllers_msgs/PointHeadFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cce80d27fd763682da8805a73316cab4"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float64 pointing_angle_error\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pointing_angle_error);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pointing_angle_error);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pointing_angle_error);
    return size;
  }

  typedef boost::shared_ptr< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PointHeadFeedback
typedef  ::pr2_controllers_msgs::PointHeadFeedback_<std::allocator<void> > PointHeadFeedback;

typedef boost::shared_ptr< ::pr2_controllers_msgs::PointHeadFeedback> PointHeadFeedbackPtr;
typedef boost::shared_ptr< ::pr2_controllers_msgs::PointHeadFeedback const> PointHeadFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_controllers_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cce80d27fd763682da8805a73316cab4";
  }

  static const char* value(const  ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcce80d27fd763682ULL;
  static const uint64_t static_value2 = 0xda8805a73316cab4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_controllers_msgs/PointHeadFeedback";
  }

  static const char* value(const  ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float64 pointing_angle_error\n\
\n\
";
  }

  static const char* value(const  ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pointing_angle_error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PointHeadFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_controllers_msgs::PointHeadFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "pointing_angle_error: ";
    Printer<double>::stream(s, indent + "  ", v.pointing_angle_error);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_CONTROLLERS_MSGS_MESSAGE_POINTHEADFEEDBACK_H

