/* Auto-generated by genmsg_cpp for file /home/billy/ros/stacks/pr2_controllers_msgs/msg/Pr2GripperCommand.msg */
#ifndef PR2_CONTROLLERS_MSGS_MESSAGE_PR2GRIPPERCOMMAND_H
#define PR2_CONTROLLERS_MSGS_MESSAGE_PR2GRIPPERCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pr2_controllers_msgs
{
template <class ContainerAllocator>
struct Pr2GripperCommand_ {
  typedef Pr2GripperCommand_<ContainerAllocator> Type;

  Pr2GripperCommand_()
  : position(0.0)
  , max_effort(0.0)
  {
  }

  Pr2GripperCommand_(const ContainerAllocator& _alloc)
  : position(0.0)
  , max_effort(0.0)
  {
  }

  typedef double _position_type;
  double position;

  typedef double _max_effort_type;
  double max_effort;


private:
  static const char* __s_getDataType_() { return "pr2_controllers_msgs/Pr2GripperCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "680acaff79486f017132a7f198d40f08"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 position\n\
float64 max_effort\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, position);
    ros::serialization::serialize(stream, max_effort);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, position);
    ros::serialization::deserialize(stream, max_effort);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(position);
    size += ros::serialization::serializationLength(max_effort);
    return size;
  }

  typedef boost::shared_ptr< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Pr2GripperCommand
typedef  ::pr2_controllers_msgs::Pr2GripperCommand_<std::allocator<void> > Pr2GripperCommand;

typedef boost::shared_ptr< ::pr2_controllers_msgs::Pr2GripperCommand> Pr2GripperCommandPtr;
typedef boost::shared_ptr< ::pr2_controllers_msgs::Pr2GripperCommand const> Pr2GripperCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_controllers_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "680acaff79486f017132a7f198d40f08";
  }

  static const char* value(const  ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x680acaff79486f01ULL;
  static const uint64_t static_value2 = 0x7132a7f198d40f08ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_controllers_msgs/Pr2GripperCommand";
  }

  static const char* value(const  ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 position\n\
float64 max_effort\n\
\n\
";
  }

  static const char* value(const  ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.max_effort);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pr2GripperCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_controllers_msgs::Pr2GripperCommand_<ContainerAllocator> & v) 
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "max_effort: ";
    Printer<double>::stream(s, indent + "  ", v.max_effort);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_CONTROLLERS_MSGS_MESSAGE_PR2GRIPPERCOMMAND_H

