"""autogenerated by genmsg_py from Pr2GripperCommandGoal.msg. Do not edit."""
import roslib.message
import struct

import pr2_controllers_msgs.msg

class Pr2GripperCommandGoal(roslib.message.Message):
  _md5sum = "86fd82f4ddc48a4cb6856cfa69217e43"
  _type = "pr2_controllers_msgs/Pr2GripperCommandGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
pr2_controllers_msgs/Pr2GripperCommand command

================================================================================
MSG: pr2_controllers_msgs/Pr2GripperCommand
float64 position
float64 max_effort

"""
  __slots__ = ['command']
  _slot_types = ['pr2_controllers_msgs/Pr2GripperCommand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       command
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Pr2GripperCommandGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.command is None:
        self.command = pr2_controllers_msgs.msg.Pr2GripperCommand()
    else:
      self.command = pr2_controllers_msgs.msg.Pr2GripperCommand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.command.position, _x.command.max_effort))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.command is None:
        self.command = pr2_controllers_msgs.msg.Pr2GripperCommand()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.command.position, _x.command.max_effort,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.command.position, _x.command.max_effort))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.command is None:
        self.command = pr2_controllers_msgs.msg.Pr2GripperCommand()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.command.position, _x.command.max_effort,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2d = struct.Struct("<2d")
