"""autogenerated by genmsg_py from SingleJointPositionGoal.msg. Do not edit."""
import roslib.message
import struct

import roslib.rostime

class SingleJointPositionGoal(roslib.message.Message):
  _md5sum = "fbaaa562a23a013fd5053e5f72cbb35c"
  _type = "pr2_controllers_msgs/SingleJointPositionGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 position
duration min_duration
float64 max_velocity

"""
  __slots__ = ['position','min_duration','max_velocity']
  _slot_types = ['float64','duration','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       position,min_duration,max_velocity
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SingleJointPositionGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = 0.
      if self.min_duration is None:
        self.min_duration = roslib.rostime.Duration()
      if self.max_velocity is None:
        self.max_velocity = 0.
    else:
      self.position = 0.
      self.min_duration = roslib.rostime.Duration()
      self.max_velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_d2id.pack(_x.position, _x.min_duration.secs, _x.min_duration.nsecs, _x.max_velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.min_duration is None:
        self.min_duration = roslib.rostime.Duration()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.position, _x.min_duration.secs, _x.min_duration.nsecs, _x.max_velocity,) = _struct_d2id.unpack(str[start:end])
      self.min_duration.canon()
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_d2id.pack(_x.position, _x.min_duration.secs, _x.min_duration.nsecs, _x.max_velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.min_duration is None:
        self.min_duration = roslib.rostime.Duration()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.position, _x.min_duration.secs, _x.min_duration.nsecs, _x.max_velocity,) = _struct_d2id.unpack(str[start:end])
      self.min_duration.canon()
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_d2id = struct.Struct("<d2id")
